#!/bin/bash

# DeviceMon Web Application Startup Script
# Professional version with improved UI/UX and error handling

echo "════════════════════════════════════════════════════════════"
echo "  DeviceMon Web Application - Professional Edition"
echo "════════════════════════════════════════════════════════════"
echo ""

# Color codes for better output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo -e "${RED}Error: Node.js is not installed.${NC}"
    echo "Please install Node.js 18+ and try again."
    echo "Download from: https://nodejs.org/"
    exit 1
fi

# Check Node.js version
NODE_VERSION=$(node -v | cut -d'.' -f1 | cut -d'v' -f2)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Error: Node.js version 18+ is required.${NC}"
    echo "Current version: $(node -v)"
    echo "Please upgrade Node.js and try again."
    exit 1
fi

echo -e "${GREEN}✓${NC} Node.js version: $(node -v)"

# Install dependencies if node_modules don't exist
if [ ! -d "node_modules" ] || [ ! -d "client/node_modules" ]; then
    echo ""
    echo -e "${YELLOW}Installing dependencies...${NC}"
    npm run install:all
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓${NC} Dependencies installed successfully"
    else
        echo -e "${RED}✗${NC} Failed to install dependencies"
        exit 1
    fi
fi

# Create logs directory if it doesn't exist
mkdir -p logs

# Create .env file if it doesn't exist
if [ ! -f "client/.env" ]; then
    echo ""
    echo -e "${YELLOW}Creating default .env configuration...${NC}"
    cat > client/.env << 'EOF'
# DeviceMon Web Client Configuration
# Generated by start.sh

# Build optimizations
TSC_COMPILE_ON_ERROR=true
GENERATE_SOURCEMAP=false

# Server URL (default: auto-detect from browser location)
# Uncomment and modify to override:
# REACT_APP_SERVER_URL=http://localhost:3002
EOF
    echo -e "${GREEN}✓${NC} Created client/.env with default configuration"
fi

echo ""
echo "════════════════════════════════════════════════════════════"

# Check if this is development or production
if [ "$1" == "dev" ] || [ "$1" == "development" ]; then
    echo -e "${BLUE}Starting in DEVELOPMENT mode...${NC}"
    echo ""
    echo "New Features in this version:"
    echo "  • Modern, professional UI theme"
    echo "  • Error boundaries (no more crashes!)"
    echo "  • Toast notifications for user feedback"
    echo "  • Input validation and error handling"
    echo "  • Loading states for better UX"
    echo ""
    echo "Server: http://localhost:3002"
    echo "Client: http://localhost:3000"
    echo ""
    echo -e "${YELLOW}Press Ctrl+C to stop both server and client${NC}"
    echo "════════════════════════════════════════════════════════════"
    npm run dev

elif [ "$1" == "build" ]; then
    echo -e "${BLUE}Building application for production...${NC}"
    echo ""
    echo "This may take a few minutes..."
    echo ""

    # Ensure fresh map files are copied to public folder
    echo -e "${YELLOW}Ensuring latest map files are in place...${NC}"
    if [ -f "client/public/maps/registers.map" ]; then
        echo -e "${GREEN}✓${NC} Map files present in client/public/maps/"
    else
        echo -e "${RED}✗${NC} Warning: Map files not found in client/public/maps/"
    fi

    # Increase Node memory for build to avoid out-of-memory errors
    export NODE_OPTIONS="--max-old-space-size=4096"

    npm run build

    if [ $? -eq 0 ]; then
        # Copy fresh map files to build directory (overwrite built versions)
        echo ""
        echo -e "${YELLOW}Copying fresh map files to build directory...${NC}"
        if [ -d "client/build/maps" ]; then
            cp -f client/public/maps/*.map client/build/maps/ 2>/dev/null && \
            echo -e "${GREEN}✓${NC} Fresh map files copied to build/maps/" || \
            echo -e "${YELLOW}⚠${NC} No .map files found to copy"
        else
            echo -e "${YELLOW}⚠${NC} Build maps directory not found, skipping map copy"
        fi

        echo ""
        echo -e "${GREEN}✓ Build completed successfully!${NC}"
        echo ""
        echo "Build artifacts are in:"
        echo "  • Server: /home/sofian/UserWorkspace/devicemonApps/devicemon-web/dist/"
        echo "  • Client: /home/sofian/UserWorkspace/devicemonApps/devicemon-web/client/build/"
        echo ""
        echo "To start in production mode, run:"
        echo "  ./start.sh prod"
        echo ""
        echo "Or deploy the build folder to your web server."
    else
        echo ""
        echo -e "${RED}✗ Build failed!${NC}"
        echo "Check the error messages above for details."
        echo ""
        echo "Common issues:"
        echo "  • Out of memory: The script increases memory to 4GB automatically"
        echo "  • TypeScript errors: Check your code for type issues"
        echo "  • Missing dependencies: Run 'npm run install:all'"
        exit 1
    fi

else
    echo -e "${BLUE}Starting in PRODUCTION mode...${NC}"
    echo ""

    # Check if build exists
    if [ ! -d "client/build" ] || [ ! -d "dist" ]; then
        echo -e "${YELLOW}Build not found. Building application first...${NC}"
        echo ""

        # Ensure fresh map files are copied to public folder
        echo -e "${YELLOW}Ensuring latest map files are in place...${NC}"
        if [ -f "client/public/maps/registers.map" ]; then
            echo -e "${GREEN}✓${NC} Map files present in client/public/maps/"
        else
            echo -e "${RED}✗${NC} Warning: Map files not found in client/public/maps/"
        fi

        export NODE_OPTIONS="--max-old-space-size=4096"
        npm run build

        if [ $? -ne 0 ]; then
            echo ""
            echo -e "${RED}✗ Build failed! Cannot start in production mode.${NC}"
            exit 1
        fi

        # Copy fresh map files to build directory (overwrite built versions)
        echo ""
        echo -e "${YELLOW}Copying fresh map files to build directory...${NC}"
        if [ -d "client/build/maps" ]; then
            cp -f client/public/maps/*.map client/build/maps/ 2>/dev/null && \
            echo -e "${GREEN}✓${NC} Fresh map files copied to build/maps/" || \
            echo -e "${YELLOW}⚠${NC} No .map files found to copy"
        fi
    fi

    # Always copy fresh map files before starting (in case they were modified)
    echo ""
    echo -e "${YELLOW}Ensuring latest map files are active...${NC}"
    if [ -d "client/build/maps" ]; then
        cp -f client/public/maps/*.map client/build/maps/ 2>/dev/null && \
        echo -e "${GREEN}✓${NC} Latest map files copied to build/maps/" || \
        echo -e "${YELLOW}⚠${NC} No .map files found to copy"
    fi

    echo ""
    echo -e "${GREEN}✓${NC} Starting server on http://localhost:3002"
    echo ""
    echo "Professional features active:"
    echo "  ✓ Modern UI theme"
    echo "  ✓ Error boundaries"
    echo "  ✓ Toast notifications"
    echo "  ✓ Input validation"
    echo "  ✓ Production optimizations"
    echo "  ✓ Fresh default maps"
    echo ""
    echo -e "${YELLOW}Press Ctrl+C to stop${NC}"
    echo "════════════════════════════════════════════════════════════"

    export NODE_ENV=production
    npm start
fi