import React from 'react';
import {
  Add as AddIcon,
  Delete as DeleteIcon,
  PlayArrow,
  Stop,
  Refresh,
  Power,
  PowerOff,
  Upload,
  Download,
  Send,
  Save,
  Check,
  Close,
  Warning,
  Info,
  Settings,
  Build,
  Lock,
  LockOpen,
  Visibility,
  VisibilityOff,
  Home,
  Dashboard,
  Timeline,
  Assessment,
  Storage,
  Memory,
  BrightnessHigh,
  BrightnessLow,
  VolumeUp,
  VolumeOff,
  Speed,
  ThermostatAuto,
  WbSunny,
  Nightlight,
  Bolt,
  ElectricBolt,
  // Additional icons
  Pause,
  SkipNext,
  SkipPrevious,
  FastForward,
  FastRewind,
  Repeat,
  Shuffle,
  Edit,
  ContentCopy,
  ContentCut,
  ContentPaste,
  Print,
  Share,
  Favorite,
  Star,
  Notifications,
  NotificationsOff,
  Alarm,
  AlarmOn,
  Timer,
  Schedule,
  CalendarToday,
  Event,
  ArrowUpward,
  ArrowDownward,
  ArrowBack,
  ArrowForward,
  TrendingUp,
  TrendingDown,
  TrendingFlat,
  ZoomIn,
  ZoomOut,
  Fullscreen,
  FullscreenExit,
  Remove,
  Block,
  Done,
  DoneAll,
  Error,
  HelpOutline,
  Report,
  Lightbulb,
  FlashOn,
  FlashOff,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothDisabled,
  Mic,
  MicOff,
  Videocam,
  VideocamOff,
  Call,
  CallEnd,
  PhoneAndroid,
  Computer,
  Laptop,
  Keyboard,
  Mouse,
  Router,
  DeviceHub,
  Sensors,
  DeveloperBoard,
  Air,
  AcUnit,
  LocalFireDepartment,
  WaterDrop,
  Opacity,
  Cloud,
  CloudOff,
  Thunderstorm,
  FilterDrama,
  NightsStay,
  Grade,
  Stars,
  WbIncandescent,
  FluorescentOutlined,
  Flag,
  Bookmark,
  LocalOffer,
  Label,
  ShoppingCart,
  AttachMoney,
  TrendingUp as Analytics,
  BarChart,
  PieChart,
  ShowChart,
  MultilineChart,
  BubbleChart,
  ScatterPlot,
  OpenInNew,
  Launch,
  Link,
  LinkOff,
  AttachFile,
  CloudUpload,
  CloudDownload,
  Sync,
  SyncDisabled,
  CachedOutlined,
  Loop,
  Autorenew,
  Update,
  SystemUpdate,
  GetApp,
  Publish,
  Undo,
  Redo,
  Reply,
  Forward as ForwardIcon,
  Search,
  FilterList,
  Sort,
  ViewList,
  ViewModule,
  ViewQuilt,
  GridView,
  RestartAlt
} from '@mui/icons-material';

export interface IconOption {
  name: string;
  value: string;
  Icon?: React.ComponentType<any>;
}

// Available icons for button widgets
export const AVAILABLE_ICONS: IconOption[] = [
  { name: 'None', value: '' },
  // Media Controls
  { name: 'Play', value: 'PlayArrow', Icon: PlayArrow },
  { name: 'Pause', value: 'Pause', Icon: Pause },
  { name: 'Stop', value: 'Stop', Icon: Stop },
  { name: 'Skip Next', value: 'SkipNext', Icon: SkipNext },
  { name: 'Skip Previous', value: 'SkipPrevious', Icon: SkipPrevious },
  { name: 'Fast Forward', value: 'FastForward', Icon: FastForward },
  { name: 'Fast Rewind', value: 'FastRewind', Icon: FastRewind },
  { name: 'Repeat', value: 'Repeat', Icon: Repeat },
  { name: 'Shuffle', value: 'Shuffle', Icon: Shuffle },
  // Basic Actions
  { name: 'Add', value: 'AddIcon', Icon: AddIcon },
  { name: 'Remove', value: 'Remove', Icon: Remove },
  { name: 'Delete', value: 'DeleteIcon', Icon: DeleteIcon },
  { name: 'Edit', value: 'Edit', Icon: Edit },
  { name: 'Check', value: 'Check', Icon: Check },
  { name: 'Done All', value: 'DoneAll', Icon: DoneAll },
  { name: 'Close', value: 'Close', Icon: Close },
  { name: 'Block', value: 'Block', Icon: Block },
  { name: 'Save', value: 'Save', Icon: Save },
  { name: 'Send', value: 'Send', Icon: Send },
  { name: 'Share', value: 'Share', Icon: Share },
  { name: 'Print', value: 'Print', Icon: Print },
  { name: 'Copy', value: 'ContentCopy', Icon: ContentCopy },
  { name: 'Cut', value: 'ContentCut', Icon: ContentCut },
  { name: 'Paste', value: 'ContentPaste', Icon: ContentPaste },
  { name: 'Undo', value: 'Undo', Icon: Undo },
  { name: 'Redo', value: 'Redo', Icon: Redo },
  // Power & System
  { name: 'Power On', value: 'Power', Icon: Power },
  { name: 'Power Off', value: 'PowerOff', Icon: PowerOff },
  { name: 'Refresh', value: 'Refresh', Icon: Refresh },
  { name: 'Restart', value: 'RestartAlt', Icon: RestartAlt },
  { name: 'Sync', value: 'Sync', Icon: Sync },
  { name: 'Sync Disabled', value: 'SyncDisabled', Icon: SyncDisabled },
  { name: 'Loop', value: 'Loop', Icon: Loop },
  { name: 'Auto Renew', value: 'Autorenew', Icon: Autorenew },
  { name: 'Update', value: 'Update', Icon: Update },
  { name: 'System Update', value: 'SystemUpdate', Icon: SystemUpdate },
  // Upload/Download
  { name: 'Upload', value: 'Upload', Icon: Upload },
  { name: 'Download', value: 'Download', Icon: Download },
  { name: 'Cloud Upload', value: 'CloudUpload', Icon: CloudUpload },
  { name: 'Cloud Download', value: 'CloudDownload', Icon: CloudDownload },
  { name: 'Get App', value: 'GetApp', Icon: GetApp },
  { name: 'Publish', value: 'Publish', Icon: Publish },
  // Notifications & Status
  { name: 'Warning', value: 'Warning', Icon: Warning },
  { name: 'Error', value: 'Error', Icon: Error },
  { name: 'Info', value: 'Info', Icon: Info },
  { name: 'Help', value: 'HelpOutline', Icon: HelpOutline },
  { name: 'Report', value: 'Report', Icon: Report },
  { name: 'Notifications', value: 'Notifications', Icon: Notifications },
  { name: 'Notifications Off', value: 'NotificationsOff', Icon: NotificationsOff },
  { name: 'Alarm', value: 'Alarm', Icon: Alarm },
  { name: 'Alarm On', value: 'AlarmOn', Icon: AlarmOn },
  // Settings & Config
  { name: 'Settings', value: 'Settings', Icon: Settings },
  { name: 'Build', value: 'Build', Icon: Build },
  { name: 'Lock', value: 'Lock', Icon: Lock },
  { name: 'Unlock', value: 'LockOpen', Icon: LockOpen },
  { name: 'Show', value: 'Visibility', Icon: Visibility },
  { name: 'Hide', value: 'VisibilityOff', Icon: VisibilityOff },
  // Navigation
  { name: 'Home', value: 'Home', Icon: Home },
  { name: 'Dashboard', value: 'Dashboard', Icon: Dashboard },
  { name: 'Arrow Up', value: 'ArrowUpward', Icon: ArrowUpward },
  { name: 'Arrow Down', value: 'ArrowDownward', Icon: ArrowDownward },
  { name: 'Arrow Back', value: 'ArrowBack', Icon: ArrowBack },
  { name: 'Arrow Forward', value: 'ArrowForward', Icon: ArrowForward },
  { name: 'Reply', value: 'Reply', Icon: Reply },
  { name: 'Forward', value: 'ForwardIcon', Icon: ForwardIcon },
  { name: 'Open In New', value: 'OpenInNew', Icon: OpenInNew },
  { name: 'Launch', value: 'Launch', Icon: Launch },
  // Data & Charts
  { name: 'Timeline', value: 'Timeline', Icon: Timeline },
  { name: 'Assessment', value: 'Assessment', Icon: Assessment },
  { name: 'Trending Up', value: 'TrendingUp', Icon: TrendingUp },
  { name: 'Trending Down', value: 'TrendingDown', Icon: TrendingDown },
  { name: 'Trending Flat', value: 'TrendingFlat', Icon: TrendingFlat },
  { name: 'Bar Chart', value: 'BarChart', Icon: BarChart },
  { name: 'Pie Chart', value: 'PieChart', Icon: PieChart },
  { name: 'Show Chart', value: 'ShowChart', Icon: ShowChart },
  { name: 'Multiline Chart', value: 'MultilineChart', Icon: MultilineChart },
  { name: 'Bubble Chart', value: 'BubbleChart', Icon: BubbleChart },
  { name: 'Scatter Plot', value: 'ScatterPlot', Icon: ScatterPlot },
  // Devices & Hardware
  { name: 'Storage', value: 'Storage', Icon: Storage },
  { name: 'Memory', value: 'Memory', Icon: Memory },
  { name: 'Phone', value: 'PhoneAndroid', Icon: PhoneAndroid },
  { name: 'Computer', value: 'Computer', Icon: Computer },
  { name: 'Laptop', value: 'Laptop', Icon: Laptop },
  { name: 'Keyboard', value: 'Keyboard', Icon: Keyboard },
  { name: 'Mouse', value: 'Mouse', Icon: Mouse },
  { name: 'Router', value: 'Router', Icon: Router },
  { name: 'Device Hub', value: 'DeviceHub', Icon: DeviceHub },
  { name: 'Sensors', value: 'Sensors', Icon: Sensors },
  { name: 'Developer Board', value: 'DeveloperBoard', Icon: DeveloperBoard },
  // Connectivity
  { name: 'Wifi', value: 'Wifi', Icon: Wifi },
  { name: 'Wifi Off', value: 'WifiOff', Icon: WifiOff },
  { name: 'Bluetooth', value: 'Bluetooth', Icon: Bluetooth },
  { name: 'Bluetooth Disabled', value: 'BluetoothDisabled', Icon: BluetoothDisabled },
  { name: 'Link', value: 'Link', Icon: Link },
  { name: 'Link Off', value: 'LinkOff', Icon: LinkOff },
  { name: 'Attach File', value: 'AttachFile', Icon: AttachFile },
  // Communication
  { name: 'Call', value: 'Call', Icon: Call },
  { name: 'Call End', value: 'CallEnd', Icon: CallEnd },
  { name: 'Mic', value: 'Mic', Icon: Mic },
  { name: 'Mic Off', value: 'MicOff', Icon: MicOff },
  { name: 'Videocam', value: 'Videocam', Icon: Videocam },
  { name: 'Videocam Off', value: 'VideocamOff', Icon: VideocamOff },
  // Lighting & Display
  { name: 'Brightness High', value: 'BrightnessHigh', Icon: BrightnessHigh },
  { name: 'Brightness Low', value: 'BrightnessLow', Icon: BrightnessLow },
  { name: 'Lightbulb', value: 'Lightbulb', Icon: Lightbulb },
  { name: 'Flash On', value: 'FlashOn', Icon: FlashOn },
  { name: 'Flash Off', value: 'FlashOff', Icon: FlashOff },
  { name: 'Incandescent', value: 'WbIncandescent', Icon: WbIncandescent },
  { name: 'Fluorescent', value: 'FluorescentOutlined', Icon: FluorescentOutlined },
  // Audio
  { name: 'Volume Up', value: 'VolumeUp', Icon: VolumeUp },
  { name: 'Volume Off', value: 'VolumeOff', Icon: VolumeOff },
  // Weather & Environment
  { name: 'Sun', value: 'WbSunny', Icon: WbSunny },
  { name: 'Moon', value: 'Nightlight', Icon: Nightlight },
  { name: 'Nights Stay', value: 'NightsStay', Icon: NightsStay },
  { name: 'Cloud', value: 'Cloud', Icon: Cloud },
  { name: 'Cloud Off', value: 'CloudOff', Icon: CloudOff },
  { name: 'Thunderstorm', value: 'Thunderstorm', Icon: Thunderstorm },
  { name: 'Filter Drama', value: 'FilterDrama', Icon: FilterDrama },
  { name: 'Air', value: 'Air', Icon: Air },
  { name: 'AC Unit', value: 'AcUnit', Icon: AcUnit },
  { name: 'Fire', value: 'LocalFireDepartment', Icon: LocalFireDepartment },
  { name: 'Water Drop', value: 'WaterDrop', Icon: WaterDrop },
  { name: 'Opacity', value: 'Opacity', Icon: Opacity },
  // Temperature & Climate
  { name: 'Thermostat', value: 'ThermostatAuto', Icon: ThermostatAuto },
  // Electrical
  { name: 'Bolt', value: 'Bolt', Icon: Bolt },
  { name: 'Electric', value: 'ElectricBolt', Icon: ElectricBolt },
  { name: 'Speed', value: 'Speed', Icon: Speed },
  // Favorites & Markers
  { name: 'Favorite', value: 'Favorite', Icon: Favorite },
  { name: 'Star', value: 'Star', Icon: Star },
  { name: 'Grade', value: 'Grade', Icon: Grade },
  { name: 'Stars', value: 'Stars', Icon: Stars },
  { name: 'Flag', value: 'Flag', Icon: Flag },
  { name: 'Bookmark', value: 'Bookmark', Icon: Bookmark },
  { name: 'Label', value: 'Label', Icon: Label },
  // Time & Schedule
  { name: 'Timer', value: 'Timer', Icon: Timer },
  { name: 'Schedule', value: 'Schedule', Icon: Schedule },
  { name: 'Calendar', value: 'CalendarToday', Icon: CalendarToday },
  { name: 'Event', value: 'Event', Icon: Event },
  // View & Display
  { name: 'Zoom In', value: 'ZoomIn', Icon: ZoomIn },
  { name: 'Zoom Out', value: 'ZoomOut', Icon: ZoomOut },
  { name: 'Fullscreen', value: 'Fullscreen', Icon: Fullscreen },
  { name: 'Fullscreen Exit', value: 'FullscreenExit', Icon: FullscreenExit },
  { name: 'View List', value: 'ViewList', Icon: ViewList },
  { name: 'View Module', value: 'ViewModule', Icon: ViewModule },
  { name: 'View Quilt', value: 'ViewQuilt', Icon: ViewQuilt },
  { name: 'Grid View', value: 'GridView', Icon: GridView },
  // Tools
  { name: 'Search', value: 'Search', Icon: Search },
  { name: 'Filter List', value: 'FilterList', Icon: FilterList },
  { name: 'Sort', value: 'Sort', Icon: Sort }
];
