import { MapEntry, DataAccessPermit } from '../maps/mapParser';

/**
 * Generate C-style header file content from map entries
 * @param entries Array of map entries to convert to .h format
 * @param isRegisterMap If true, generates register header, otherwise parameter header
 * @param profileName Optional profile name to include in comments
 * @returns Generated .h file content as string
 */
export function generateHeaderFile(
  entries: MapEntry[],
  isRegisterMap: boolean,
  profileName: string = 'Custom'
): string {
  const lines: string[] = [];
  const fileName = isRegisterMap ? 'ds_register_names.h' : 'ds_parameter_names.h';
  const guardName = isRegisterMap ? 'DS_REGISTER_NAMES_H_' : 'DS_PARAMETER_NAMES_H_';
  const structName = isRegisterMap ? 'ds_register_names_t' : 'ds_parameter_names_t';
  const dataType = isRegisterMap ? 'Registers' : 'Parameters';

  // Header comment
  lines.push('/*');
  lines.push(` * ${fileName}`);
  lines.push(' *');
  lines.push(` * ${dataType} definitions for datastream library`);
  lines.push(` * Generated by DSHub Map Editor`);
  lines.push(` * Profile: ${profileName}`);
  lines.push(' *');
  lines.push(` * Created: ${new Date().toLocaleDateString('en-GB')}`);
  lines.push(' *');
  if (isRegisterMap) {
    lines.push(' * Note: System registers (cmd 6) are library-managed and are NOT included in this file.');
    lines.push(' *       For system register definitions, see ds_system_register_names.h in the datastream library.');
  }
  lines.push(' */');
  lines.push('');

  // Header guard
  lines.push(`#ifndef ${guardName}`);
  lines.push(`#define ${guardName}`);
  lines.push('');

  // Include
  lines.push('/******* include files with user defines types (must be 32bit - 4 bytes long) ******/');
  lines.push('#include <ds_default_config.h>');
  lines.push('/************************************************************************************/');
  lines.push('');

  // Description comment
  lines.push(`/************************************* ${dataType.toUpperCase()} ****************************************`);
  lines.push(`* ${dataType} definitions - customize for your application${' '.repeat(Math.max(0, 25 - dataType.length))}*`);
  lines.push('* All data must be 32-bit aligned: uint32_t, int32_t, float, etc.                     *');
  if (isRegisterMap) {
    lines.push('* Registers hold real-time data accessible via datastream protocol                     *');
    lines.push('* The registers are read-only or read/write, depending on the application              *');
  } else {
    lines.push('* Parameters hold persistent configuration data stored in flash memory                 *');
    lines.push('* Parameters are designed to be stored in permanent storage (e.g. flash)               *');
  }
  lines.push('****************************************************************************************/');

  // Struct definition
  lines.push('typedef struct PACKED');
  lines.push('{');

  if (isRegisterMap) {
    // For registers, group by access permission
    const readOnlyEntries = getConsolidatedEntries(
      entries.filter(e => e.accessPermit === DataAccessPermit.READ_ONLY)
    );
    const readWriteEntries = getConsolidatedEntries(
      entries.filter(e => e.accessPermit === DataAccessPermit.READ_WRITE)
    );

    if (readOnlyEntries.length > 0) {
      lines.push('    /***** read only registers *****/');
      readOnlyEntries.forEach(entry => {
        lines.push(formatHeaderEntry(entry));
      });
      lines.push('');
    }

    if (readWriteEntries.length > 0) {
      lines.push('    /***** read/write registers *****/');
      readWriteEntries.forEach(entry => {
        lines.push(formatHeaderEntry(entry));
      });
      lines.push('');
    }
  } else {
    // For parameters, just list all entries
    const consolidatedEntries = getConsolidatedEntries(entries);
    consolidatedEntries.forEach(entry => {
      lines.push(formatHeaderEntry(entry));
    });
    lines.push('');
  }

  lines.push(`}${structName};`);

  // Add read-only count macro for registers
  if (isRegisterMap) {
    const readOnlyCount = entries.filter(e => e.accessPermit === DataAccessPermit.READ_ONLY).length;
    lines.push(`#define DS_REGISTERS_READ_ONLY_COUNT    ${readOnlyCount}`);
  }

  lines.push('');
  lines.push(`#endif /* ${guardName} */`);

  return lines.join('\n');
}

/**
 * Format a single map entry as a C struct field
 * @param entry The map entry to format
 * @returns Formatted struct field (e.g., "    uint32_t    NAME;" or "    int    ARRAY[4];")
 */
function formatHeaderEntry(entry: MapEntry): string {
  // Convert 'hex' to 'uint32_t' for C header files (C doesn't understand 'hex' type)
  const type = entry.type === 'hex' ? 'uint32_t' : entry.type;
  const name = entry.name.replace(/\[\d+\]$/, ''); // Remove array index if present

  // Add padding for alignment (common C style)
  const typePadding = ' '.repeat(Math.max(1, 16 - type.length));

  let line: string;
  if (entry.isArray && entry.arraySize) {
    line = `    ${type}${typePadding}${name}[${entry.arraySize}];`;
  } else {
    line = `    ${type}${typePadding}${name};`;
  }

  if (entry.unit) {
    line += `    /* ${entry.unit} */`;
  }

  const commentParts: string[] = [];
  if (entry.description) commentParts.push(entry.description);
  if (entry.valueList?.length) {
    commentParts.push('Values: ' + entry.valueList.map(v => `${v.value}=${v.label}`).join(', '));
  }
  if (commentParts.length > 0) {
    return `    /** ${commentParts.join(' | ')} */\n${line}`;
  }

  return line;
}

/**
 * Consolidate array entries back to single array declarations
 * Map parser expands arrays into individual entries (e.g., IP_ADDR[0], IP_ADDR[1])
 * This function consolidates them back to single entries (e.g., IP_ADDR with arraySize=4)
 * @param entries Original parsed entries
 * @returns Consolidated entries with arrays merged
 */
function getConsolidatedEntries(entries: MapEntry[]): MapEntry[] {
  const consolidated: MapEntry[] = [];
  const processedArrays = new Set<string>();

  entries.forEach(entry => {
    // Check if this is an array element (has [index] in name)
    const arrayMatch = entry.name.match(/^(.+)\[(\d+)\]$/);

    if (arrayMatch) {
      const baseName = arrayMatch[1];

      // Skip if we already processed this array
      if (processedArrays.has(baseName)) {
        return;
      }

      // Find all entries with the same base name
      const arrayEntries = entries.filter(e => {
        const match = e.name.match(/^(.+)\[(\d+)\]$/);
        return match && match[1] === baseName;
      });

      // Calculate array size
      const arraySize = arrayEntries.length;

      // Create consolidated entry — preserve metadata from first element
      consolidated.push({
        address: entry.address,
        name: baseName,
        type: entry.type,
        isArray: true,
        arraySize: arraySize,
        accessPermit: entry.accessPermit,
        showAsHex: entry.showAsHex,
        unit: entry.unit,
        description: entry.description,
        valueList: entry.valueList,
      });

      processedArrays.add(baseName);
    } else if (!entry.isArray) {
      // Regular non-array entry
      consolidated.push(entry);
    }
  });

  return consolidated;
}
