import { MapEntry, DataAccessPermit, DataForm } from '../maps/mapParser';

/**
 * Generate .map file content from an array of map entries
 * @param entries Array of map entries to convert to .map format
 * @param isRegisterMap If true, includes read/write boundary markers
 * @returns Generated .map file content as string
 */
export function generateMapFile(entries: MapEntry[], isRegisterMap: boolean = false): string {
  const lines: string[] = [];

  console.log(`[MapFileGenerator] Generating map file with ${entries.length} total entries`);

  // CRITICAL: Consolidate array entries before formatting to prevent duplication
  const consolidated = consolidateArrayEntries(entries);
  console.log(`[MapFileGenerator] After consolidation: ${consolidated.length} entries`);

  // Add header comment
  lines.push('// Generated by DSHub Map Editor');
  lines.push('// Note: System registers (cmd 6) are library-managed and are not included here.');
  lines.push('//       See ds_system_register_names.h in the datastream library for system register definitions.');
  lines.push('');

  if (isRegisterMap) {
    // For registers, group by access permission
    const readOnlyEntries = consolidated.filter(e => e.accessPermit === DataAccessPermit.READ_ONLY);
    const readWriteEntries = consolidated.filter(e => e.accessPermit === DataAccessPermit.READ_WRITE);

    if (readOnlyEntries.length > 0) {
      lines.push('/***** read only *****/');
      readOnlyEntries.forEach(entry => {
        lines.push(formatMapEntry(entry));
      });
      lines.push('');
    }

    if (readWriteEntries.length > 0) {
      lines.push('/***** read/write registers *****/');
      readWriteEntries.forEach(entry => {
        lines.push(formatMapEntry(entry));
      });
    }
  } else {
    // For parameters, just list all entries
    consolidated.forEach(entry => {
      lines.push(formatMapEntry(entry));
    });
  }

  return lines.join('\n');
}

/**
 * Format a single map entry as a .map file line
 * @param entry The map entry to format
 * @returns Formatted line (e.g., "uint32_t    NAME;" or "int    ARRAY[4];")
 */
function formatMapEntry(entry: MapEntry): string {
  const type = entry.type;
  const name = entry.name.replace(/\[\d+\]$/, ''); // Remove array index if present

  // Add padding for alignment (common .map file style)
  const typePadding = ' '.repeat(Math.max(1, 12 - type.length));

  let line: string;
  if (entry.isArray && entry.arraySize) {
    line = `${type}${typePadding}${name}[${entry.arraySize}];`;
  } else {
    line = `${type}${typePadding}${name};`;
  }

  if (entry.unit) {
    line += `    // [${entry.unit}]`;
  }

  return line;
}

/**
 * Consolidate array entries back to single array declarations
 * Map parser expands arrays into individual entries (e.g., IP_ADDR[0], IP_ADDR[1])
 * This function consolidates them back to single entries (e.g., IP_ADDR with arraySize=4)
 * @param entries Original parsed entries
 * @returns Consolidated entries with arrays merged
 */
export function consolidateArrayEntries(entries: MapEntry[]): MapEntry[] {
  const consolidated: MapEntry[] = [];
  const processedArrays = new Set<string>();

  console.log(`[MapFileGenerator] Consolidating ${entries.length} entries`);

  entries.forEach(entry => {
    // Check if this is an array element (has [index] in name)
    const arrayMatch = entry.name.match(/^(.+)\[(\d+)\]$/);

    if (arrayMatch) {
      const baseName = arrayMatch[1];
      const index = parseInt(arrayMatch[2], 10);

      // Skip if we already processed this array
      if (processedArrays.has(baseName)) {
        return;
      }

      // Find all entries with the same base name
      const arrayEntries = entries.filter(e => {
        const match = e.name.match(/^(.+)\[(\d+)\]$/);
        return match && match[1] === baseName;
      });

      // Calculate array size
      const arraySize = arrayEntries.length;

      console.log(`[MapFileGenerator] Consolidating array "${baseName}" with ${arraySize} elements`);

      // Create consolidated entry — preserve metadata from first element
      consolidated.push({
        address: entry.address, // Use first element's address
        name: baseName,
        type: entry.type,
        isArray: true,
        arraySize: arraySize,
        accessPermit: entry.accessPermit,
        showAsHex: entry.showAsHex,
        unit: entry.unit,
        description: entry.description,
        valueList: entry.valueList,
      });

      processedArrays.add(baseName);
    } else if (!entry.isArray) {
      // Regular non-array entry
      consolidated.push(entry);
    }
  });

  console.log(`[MapFileGenerator] Consolidated to ${consolidated.length} entries`);
  return consolidated;
}

/**
 * Validate map entry name (must be valid C identifier)
 * @param name Name to validate
 * @returns True if valid, false otherwise
 */
export function isValidMapEntryName(name: string): boolean {
  // Valid C identifier: starts with letter or underscore, followed by letters, digits, or underscores
  const cIdentifierRegex = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
  return cIdentifierRegex.test(name);
}

/**
 * Calculate the next available address based on current entries
 * @param entries Current array of entries
 * @returns Next available address
 */
export function getNextAddress(entries: MapEntry[]): number {
  if (entries.length === 0) {
    return 0;
  }

  // Find the highest address
  const maxAddress = Math.max(...entries.map(e => e.address));
  return maxAddress + 1;
}
