import jsPDF from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import { invoke } from '@tauri-apps/api/core';
import { MapEntry, DataAccessPermit } from '../maps/mapParser';
import { SysCommand } from '../types/settings';
import { consolidateArrayEntries } from './mapFileGenerator';

// ─── Colour palette ───────────────────────────────────────────────────────────
const HEADER_BG: [number, number, number] = [30, 35, 42];     // near-black
const HEADER_FG: [number, number, number] = [200, 220, 240];  // pale blue-white
const SECTION_BG: [number, number, number] = [44, 55, 68];    // section title bg
const SECTION_FG: [number, number, number] = [100, 190, 210]; // cyan accent
const ALT_ROW: [number, number, number] = [24, 29, 36];       // subtle stripe
const BODY_FG: [number, number, number] = [210, 215, 220];
const BODY_MONO_FG: [number, number, number] = [120, 210, 170]; // mint for code
const DIVIDER: [number, number, number] = [55, 65, 80];

// ─── Helpers ──────────────────────────────────────────────────────────────────

function accessLabel(permit: DataAccessPermit): string {
  return permit === DataAccessPermit.READ_ONLY ? 'R' : 'R/W';
}

function valueListText(entry: MapEntry): string {
  if (!entry.valueList || entry.valueList.length === 0) return '';
  return entry.valueList.map(v => `${v.value}: ${v.label}`).join('\n');
}

function formatType(entry: MapEntry): string {
  if (entry.isArray && entry.arraySize) {
    return `${entry.type}[${entry.arraySize}]`;
  }
  return entry.type;
}

/** Add a bold section heading row that spans the table width */
function sectionHeading(doc: jsPDF, title: string, y: number, pageWidth: number): number {
  const margin = 14;
  const w = pageWidth - margin * 2;

  doc.setFillColor(...SECTION_BG);
  doc.rect(margin, y, w, 7, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...SECTION_FG);
  doc.text(title.toUpperCase(), margin + 3, y + 5);
  return y + 9;
}

/** Draw page-number footer on every page */
function addPageNumbers(doc: jsPDF): void {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(100, 110, 120);
    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();
    doc.text(`Page ${i} of ${total}`, w - 14, h - 8, { align: 'right' });
    // bottom rule
    doc.setDrawColor(...DIVIDER);
    doc.setLineWidth(0.3);
    doc.line(14, h - 11, w - 14, h - 11);
  }
}

// ─── Main export function ─────────────────────────────────────────────────────

export async function exportMapProfilePdf(
  profileName: string,
  registerEntries: MapEntry[],
  parameterEntries: MapEntry[],
  sysCommands: SysCommand[]
): Promise<void> {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 14;

  // ── Cover / header block ──────────────────────────────────────────────────
  doc.setFillColor(...HEADER_BG);
  doc.rect(0, 0, pageW, 38, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(...HEADER_FG);
  doc.text('DSHub Map Documentation', margin, 16);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...SECTION_FG);
  doc.text(`Profile: ${profileName}`, margin, 25);

  const dateStr = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
  doc.setFontSize(8);
  doc.setTextColor(140, 155, 170);
  doc.text(dateStr, pageW - margin, 25, { align: 'right' });

  doc.setFontSize(8);
  doc.text('Generated by DSHub Map Editor', pageW - margin, 31, { align: 'right' });

  let cursorY = 46;

  // ─────────────────────────────────────────────────────────────────────────
  // REGISTERS
  // ─────────────────────────────────────────────────────────────────────────
  const regEntries = consolidateArrayEntries(registerEntries);
  cursorY = sectionHeading(doc, `Registers  (${regEntries.length} entries)`, cursorY, pageW);

  if (regEntries.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(120, 130, 140);
    doc.text('No registers defined.', margin + 3, cursorY + 4);
    cursorY += 10;
  } else {
    autoTable(doc, {
      startY: cursorY,
      margin: { left: margin, right: margin },
      theme: 'plain',
      styles: {
        fontSize: 8,
        cellPadding: { top: 2, bottom: 2, left: 3, right: 3 },
        textColor: BODY_FG,
        lineColor: DIVIDER,
        lineWidth: 0.2,
        overflow: 'linebreak',
        minCellHeight: 6
      },
      headStyles: {
        fillColor: [38, 46, 56],
        textColor: HEADER_FG,
        fontStyle: 'bold',
        fontSize: 7.5
      },
      alternateRowStyles: { fillColor: ALT_ROW },
      bodyStyles: { fillColor: [28, 33, 40] },
      columnStyles: {
        0: { cellWidth: 14, halign: 'center', fontStyle: 'bold', textColor: BODY_MONO_FG },
        1: { cellWidth: 44, fontStyle: 'bold', textColor: BODY_MONO_FG },
        2: { cellWidth: 24, fontStyle: 'normal', textColor: [150, 160, 175] },
        3: { cellWidth: 12, halign: 'center', textColor: [150, 160, 175] },
        4: { cellWidth: 16, halign: 'center', textColor: [150, 160, 175] },
        5: { cellWidth: 'auto' }
      },
      head: [[
        { content: 'Addr', styles: { halign: 'center' } },
        'Name', 'Type', 'Access', 'Unit', 'Description / Values'
      ]],
      body: regEntries.map(e => {
        const valText = valueListText(e);
        const desc = [e.description, valText].filter(Boolean).join('\n\n');
        return [
          e.address,
          e.name.replace(/\[\d+\]$/, ''),
          formatType(e),
          accessLabel(e.accessPermit),
          e.unit ?? '',
          desc
        ];
      }),
      didParseCell: (data) => {
        // Tint read-only rows subtly
        if (data.section === 'body') {
          const entry = regEntries[data.row.index];
          if (entry?.accessPermit === DataAccessPermit.READ_ONLY) {
            data.cell.styles.fillColor = data.row.index % 2 === 0
              ? [26, 32, 38]
              : [22, 27, 33];
          }
        }
      }
    });
    cursorY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // PARAMETERS
  // ─────────────────────────────────────────────────────────────────────────
  const paramEntries = consolidateArrayEntries(parameterEntries);

  if (cursorY > pageH - 40) {
    doc.addPage();
    cursorY = 16;
  }

  cursorY = sectionHeading(doc, `Parameters  (${paramEntries.length} entries)`, cursorY, pageW);

  if (paramEntries.length === 0) {
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(120, 130, 140);
    doc.text('No parameters defined.', margin + 3, cursorY + 4);
    cursorY += 10;
  } else {
    autoTable(doc, {
      startY: cursorY,
      margin: { left: margin, right: margin },
      theme: 'plain',
      styles: {
        fontSize: 8,
        cellPadding: { top: 2, bottom: 2, left: 3, right: 3 },
        textColor: BODY_FG,
        lineColor: DIVIDER,
        lineWidth: 0.2,
        overflow: 'linebreak',
        minCellHeight: 6
      },
      headStyles: {
        fillColor: [38, 46, 56],
        textColor: HEADER_FG,
        fontStyle: 'bold',
        fontSize: 7.5
      },
      alternateRowStyles: { fillColor: ALT_ROW },
      bodyStyles: { fillColor: [28, 33, 40] },
      columnStyles: {
        0: { cellWidth: 14, halign: 'center', fontStyle: 'bold', textColor: BODY_MONO_FG },
        1: { cellWidth: 50, fontStyle: 'bold', textColor: BODY_MONO_FG },
        2: { cellWidth: 28, fontStyle: 'normal', textColor: [150, 160, 175] },
        3: { cellWidth: 16, halign: 'center', textColor: [150, 160, 175] },
        4: { cellWidth: 'auto' }
      },
      head: [[
        { content: 'Addr', styles: { halign: 'center' } },
        'Name', 'Type', 'Unit', 'Description / Values'
      ]],
      body: paramEntries.map(e => {
        const valText = valueListText(e);
        const desc = [e.description, valText].filter(Boolean).join('\n\n');
        return [
          e.address,
          e.name.replace(/\[\d+\]$/, ''),
          formatType(e),
          e.unit ?? '',
          desc
        ];
      })
    });
    cursorY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // SYS_COMMANDS
  // ─────────────────────────────────────────────────────────────────────────
  if (sysCommands.length > 0) {
    if (cursorY > pageH - 40) {
      doc.addPage();
      cursorY = 16;
    }

    const sorted = [...sysCommands].sort((a, b) => a.code - b.code);
    cursorY = sectionHeading(doc, `SYS_COMMANDS  (${sorted.length} entries)`, cursorY, pageW);

    autoTable(doc, {
      startY: cursorY,
      margin: { left: margin, right: margin },
      theme: 'plain',
      styles: {
        fontSize: 8,
        cellPadding: { top: 2, bottom: 2, left: 3, right: 3 },
        textColor: BODY_FG,
        lineColor: DIVIDER,
        lineWidth: 0.2,
        overflow: 'linebreak',
        minCellHeight: 6
      },
      headStyles: {
        fillColor: [38, 46, 56],
        textColor: HEADER_FG,
        fontStyle: 'bold',
        fontSize: 7.5
      },
      alternateRowStyles: { fillColor: ALT_ROW },
      bodyStyles: { fillColor: [28, 33, 40] },
      columnStyles: {
        0: { cellWidth: 18, halign: 'center', fontStyle: 'bold', textColor: BODY_MONO_FG },
        1: { cellWidth: 70, fontStyle: 'bold', textColor: BODY_MONO_FG },
        2: { cellWidth: 'auto' }
      },
      head: [[
        { content: 'Code', styles: { halign: 'center' } },
        'Name', 'Description'
      ]],
      body: sorted.map(cmd => [
        cmd.code,
        cmd.name,
        cmd.description ?? ''
      ])
    });
  }

  // ── Page numbers ──────────────────────────────────────────────────────────
  addPageNumbers(doc);

  // ── Save via Tauri native dialog ──────────────────────────────────────────
  const safeName = profileName.replace(/[^a-zA-Z0-9_-]/g, '_');
  const suggestedName = `${safeName}_map_documentation.pdf`;

  // jsPDF outputs base64 via 'datauristring'; strip the data URI prefix
  const dataUri = doc.output('datauristring') as string;
  const base64 = dataUri.split(',')[1];

  await invoke<boolean>('save_pdf_file', { dataBase64: base64, suggestedName });
}
