import { SysCommand } from '../types/settings';

/**
 * Built-in library system commands from ds_sys_command_t.
 * These are always available in every profile and are never exported.
 */
export const DS_SYS_COMMANDS: SysCommand[] = [
  { code: 65000, name: 'ds_sys_command_READ_FLASH',     description: 'Read parameters from flash' },
  { code: 65001, name: 'ds_sys_command_WRITE_FLASH',    description: 'Write parameters to flash' },
  { code: 65002, name: 'ds_sys_command_RESET_FIRMWARE', description: 'Reset the firmware' },
];

/**
 * Generate .map file content for SYS_COMMANDs
 * @param commands Array of SysCommand entries
 * @returns Generated .map file content as string
 */
export function generateSysCommandMapFile(commands: SysCommand[]): string {
  const lines: string[] = [];

  // Header comment
  lines.push('# SYS_COMMAND Map File');
  lines.push('# Generated by DSHub Map Editor');
  lines.push(`# Created: ${new Date().toISOString()}`);
  lines.push('#');
  lines.push('# Format: CODE NAME [DESCRIPTION]');
  lines.push('# CODE: Command code (0-255)');
  lines.push('# NAME: Command name (uppercase, no spaces)');
  lines.push('# DESCRIPTION: Optional description (enclosed in quotes if contains spaces)');
  lines.push('');

  // Sort commands by code
  const sortedCommands = [...commands].sort((a, b) => a.code - b.code);

  // Write each command
  sortedCommands.forEach(cmd => {
    if (cmd.description) {
      // If description contains spaces or special chars, quote it
      const needsQuotes = /\s/.test(cmd.description);
      const description = needsQuotes ? `"${cmd.description}"` : cmd.description;
      lines.push(`${cmd.code} ${cmd.name} ${description}`);
    } else {
      lines.push(`${cmd.code} ${cmd.name}`);
    }
  });

  return lines.join('\n');
}

/**
 * Generate C header file content for SYS_COMMANDs
 * @param commands Array of SysCommand entries
 * @param profileName Optional profile name to include in comments
 * @returns Generated .h file content as string
 */
export function generateSysCommandHeaderFile(
  commands: SysCommand[],
  profileName: string = 'Custom'
): string {
  const lines: string[] = [];
  const fileName = 'ds_sys_commands.h';
  const guardName = 'DS_SYS_COMMANDS_H_';

  // Header comment
  lines.push('/*');
  lines.push(` * ${fileName}`);
  lines.push(' *');
  lines.push(' * System Command definitions for datastream library');
  lines.push(' * Generated by DSHub Map Editor');
  lines.push(` * Profile: ${profileName}`);
  lines.push(' *');
  lines.push(` * Created: ${new Date().toLocaleDateString('en-GB')}`);
  lines.push(' */');
  lines.push('');

  // Header guard
  lines.push(`#ifndef ${guardName}`);
  lines.push(`#define ${guardName}`);
  lines.push('');

  // Documentation comment
  lines.push('/*********************************** SYS_COMMANDs ************************************');
  lines.push('* System command codes for use with datastream SYS_COMMAND protocol                *');
  lines.push('* These commands are sent using command type 0x00 (SYS_COMMAND)                    *');
  lines.push('* Each command code is a unique identifier for a specific system operation         *');
  lines.push('****************************************************************************************/');
  lines.push('');

  // Enum definition
  lines.push('typedef enum');
  lines.push('{');

  // Sort commands by code
  const sortedCommands = [...commands].sort((a, b) => a.code - b.code);

  sortedCommands.forEach((cmd, index) => {
    const isLast = index === sortedCommands.length - 1;
    const comma = isLast ? '' : ',';

    // Format: NAME = CODE, // description
    if (cmd.description) {
      lines.push(`    ${cmd.name} = ${cmd.code}${comma}  // ${cmd.description}`);
    } else {
      lines.push(`    ${cmd.name} = ${cmd.code}${comma}`);
    }
  });

  lines.push('} ds_sys_command_t;');
  lines.push('');

  // Add count macro
  lines.push(`#define DS_SYS_COMMAND_COUNT    ${commands.length}`);
  lines.push('');

  // Close header guard
  lines.push(`#endif /* ${guardName} */`);

  return lines.join('\n');
}

/**
 * Parse a SYS_COMMAND .map file and extract commands
 * @param content The .map file content
 * @returns Array of SysCommand objects
 */
export function parseSysCommandMapFile(content: string): SysCommand[] {
  const commands: SysCommand[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    // Skip empty lines and comments
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    // Parse: CODE NAME [DESCRIPTION]
    // Description can be quoted if it contains spaces
    const match = trimmed.match(/^(\d+)\s+([A-Z_][A-Z0-9_]*)\s*(.*)$/);

    if (match) {
      const code = parseInt(match[1]);
      const name = match[2];
      let description = match[3].trim();

      // Remove quotes from description if present
      if (description.startsWith('"') && description.endsWith('"')) {
        description = description.slice(1, -1);
      }

      // Validate code range (0–64999; 65000–65535 reserved for library)
      if (code >= 0 && code <= 64999) {
        commands.push({
          code,
          name,
          description: description || undefined
        });
      }
    }
  }

  return commands;
}
